[versions]
androidx_annotation = "1.1.0"
androidx_app_compat = "1.2.0-rc01"
androidx_constraint_layout = "1.1.3"
androidx_core = "1.1.0"
androidx_fragment_testing = "1.1.0"
androidx_lifecycle = "2.2.0"
androidx_lifecycle_viewmodel = "2.3.0"
androidx_multidex = "2.0.1"
androidx_recycler_view = "1.1.0-beta05"
androidx_test_espresso_core = "3.1.0"
androidx_test_extensions = "1.1.1"
androidx_test_orchestrator = "1.1.0"
androidx_test_rules = "1.1.0"
androidx_test_runner = "1.1.0"
androidx_view_pager2 = "1.0.0"
google_guava = "23.6.1-android"
google_material = "1.1.0"
joda_time = "2.10.10"
junit_jupiter = "5.7.1"
kotlin_coroutines = "1.3.7"
logback_android_classic = "1.1.1-6"
logback_android_core = "1.1.1-6"
logback_classic = "1.2.3"
mockito_android = "2.22.0"
nano_httpd = "master-SNAPSHOT"
nano_httpd_nanolets = "master-SNAPSHOT"
r2_shared = "29422a6e"
r2_streamer = "2.0.0-beta.2"
rxandroid = '2.1.1'
rxjava2 = "2.2.21"
rxjavaextensions = '0.20.10'
slf4j = "1.7.25"
xmlpull = "1.1.3.1"
orgjson = "20200518"
kxml = "2.3.0"
kotlin = "1.4.20"

[libraries]
androidx_annotation = { module = "androidx.annotation:annotation", version.ref = "androidx_annotation" }
androidx_app_compat = { module = "androidx.appcompat:appcompat", version.ref = "androidx_app_compat" }
androidx_constraint_layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx_constraint_layout" }
androidx_core = { module = "androidx.core:core", version.ref = "androidx_core" }
androidx_core_ktx = { module = "androidx.core:core-ktx", version.ref = "androidx_core" }
androidx_fragment_testing = { module = "androidx.fragment:fragment-testing", version.ref = "androidx_fragment_testing" }
androidx_lifecycle = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "androidx_lifecycle" }
androidx_lifecycle_viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx_lifecycle_viewmodel" }
androidx_multidex = { module = "androidx.multidex:multidex", version.ref = "androidx_multidex" }
androidx_recycler_view = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx_recycler_view" }
androidx_test_espresso_core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx_test_espresso_core" }
androidx_test_extensions = { module = "androidx.test.ext:junit", version.ref = "androidx_test_extensions" }
androidx_test_orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidx_test_orchestrator" }
androidx_test_rules = { module = "androidx.test:rules", version.ref = "androidx_test_rules" }
androidx_test_runner = { module = "androidx.test:runner", version.ref = "androidx_test_runner" }
androidx_view_pager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx_view_pager2" }
google_guava = { module = "com.google.guava:guava", version.ref = "google_guava" }
google_material = { module = "com.google.android.material:material", version.ref = "google_material" }
joda_time = { module = "joda-time:joda-time", version.ref = "joda_time" }
junit_jupiter_api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit_jupiter" }
junit_jupiter_engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit_jupiter" }
kotlin_coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin_coroutines" }
kotlin_coroutines_android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin_coroutines" }
kotlin_stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kxml = { module = "net.sf.kxml:kxml2", version.ref = "kxml" }
logback_android_classic = { module = "com.github.tony19:logback-android-classic", version.ref = "logback_android_classic" }
logback_android_core = { module = "com.github.tony19:logback-android-core", version.ref = "logback_android_core" }
logback_classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback_classic" }
mockito_android = { module = "org.mockito:mockito-android", version.ref = "mockito_android" }
nano_httpd = { module = "com.github.edrlab.nanohttpd:nanohttpd", version.ref = "nano_httpd" }
nano_httpd_nanolets = { module = "com.github.edrlab.nanohttpd:nanohttpd-nanolets", version.ref = "nano_httpd_nanolets" }
org_json = { module = "org.json:json", version.ref = "orgjson" }
r2_shared = { module = "com.github.readium:r2-shared-kotlin", version.ref = "r2_shared" }
r2_streamer = { module = "com.github.readium:r2-streamer-kotlin", version.ref = "r2_streamer" }
rxandroid2 = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava2" }
rxjava2extensions = { module = "com.github.akarnokd:rxjava2-extensions", version.ref = "rxjavaextensions" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
xmlpull = { module = "xmlpull:xmlpull", version.ref = "xmlpull" }
